// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXsDFtdJrQT8jGf0ialFP_QSt7rvUaf0',
    appId: '1:906334483908:web:9ae96aecdf3cc688436091',
    messagingSenderId: '906334483908',
    projectId: 'xoapp-c0ae9',
    authDomain: 'xoapp-c0ae9.firebaseapp.com',
    storageBucket: 'xoapp-c0ae9.appspot.com',
    measurementId: 'G-9TVHXQCYF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOKaJT3_l-hyyJzEWfuixK89WsSR1S7c',
    appId: '1:906334483908:android:1d619af9b895abdf436091',
    messagingSenderId: '906334483908',
    projectId: 'xoapp-c0ae9',
    storageBucket: 'xoapp-c0ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCS2CaUjGBKOStmZPCduF2Cw98UTe2EtI',
    appId: '1:906334483908:ios:64953fffe6924a38436091',
    messagingSenderId: '906334483908',
    projectId: 'xoapp-c0ae9',
    storageBucket: 'xoapp-c0ae9.appspot.com',
    iosBundleId: 'com.example.xomultiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCS2CaUjGBKOStmZPCduF2Cw98UTe2EtI',
    appId: '1:906334483908:ios:64953fffe6924a38436091',
    messagingSenderId: '906334483908',
    projectId: 'xoapp-c0ae9',
    storageBucket: 'xoapp-c0ae9.appspot.com',
    iosBundleId: 'com.example.xomultiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANXsDFtdJrQT8jGf0ialFP_QSt7rvUaf0',
    appId: '1:906334483908:web:7986f64eed110ca1436091',
    messagingSenderId: '906334483908',
    projectId: 'xoapp-c0ae9',
    authDomain: 'xoapp-c0ae9.firebaseapp.com',
    storageBucket: 'xoapp-c0ae9.appspot.com',
    measurementId: 'G-8WLT7KF9YM',
  );
}
